name: amazcart
description: Amazcart Mobile App

publish_to: "none"

version: 1.0.0+22

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  get: ^4.6.5
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0
  share: ^2.0.4
  http: ^0.13.4
  image_picker: ^0.8.5+3
  dio: ^4.0.6
  persistent_bottom_nav_bar: ^4.0.2
  google_sign_in: ^5.3.2
  expandable: ^5.0.1
  octo_image: ^1.0.2
  animated_splash_screen: ^1.2.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.2
  country_code_picker: ^2.0.2
  # device_preview: ^1.0.0
  pin_code_fields: ^7.4.0
  dotted_border: ^2.0.0+2
  flutter_svg: ^1.1.0
  dotted_line: ^3.1.0
  expansion_tile_card: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^0.6.0
  slide_countdown_clock: ^1.0.3
  flutter_animation_progress_bar: ^2.2.1
  timelines: ^0.1.0
  clipboard: ^0.1.3
  extended_nested_scroll_view: ^5.1.0
  flutter_page_indicator: ^0.0.3
  transformer_page_view: ^0.1.6
  flutter_spinkit: ^5.1.0
  fancy_shimmer_image: ^2.0.2
  get_storage: ^2.0.3
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  flutter_cupertino_datetime_picker: ^3.0.0
  avatar_glow: ^2.0.2
  file_picker: ^3.0.4
  loading_skeleton: ^1.0.2
  flutter_easyloading: ^3.0.5
  scratcher: ^2.2.1
  share_plus: ^4.0.4
  radio_grouped_buttons: ^1.0.1
  animate_do: ^2.1.0
  # stripe_payment: ^1.1.4
  # flutter_stripe: ^3.0.2
  razorpay_flutter: ^1.3.0
  webview_flutter: ^2.8.0
  http_auth: ^1.0.1
  flutter_paystack: ^1.0.5+1
  # flutter_webview_plugin: ^0.4.0
  flutter_inappwebview: ^5.4.3+7
  flutterwave: ^1.0.1
  multi_select_flutter: ^4.1.2
  flutter_xlider: ^3.4.0
  loading_more_list: ^4.1.2
  supercharged: ^2.1.1
  pay: ^1.0.9
  flutter_staggered_grid_view: ^0.6.1
  photo_view: ^0.14.0
  stripe_sdk: ^5.0.0-nullsafety.1
  paytm_allinonesdk: ^1.1.7
  easy_search: ^1.0.6+1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  flutter_html: ^3.0.0-alpha.3
  # sizer: ^2.0.15
  dio_http_cache: ^0.3.0
  json_serializable: ^4.1.4
  # json_annotation: ^4.1.0
  platform: ^3.1.0

# dependency_overrides:
#   json_serializable: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.1
  flutter_launcher_icons: ^0.9.2
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/config/app_logo.jpg"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FF3364"
  image: assets/config/splash_screen_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/config/
    - assets/fonts/
    - assets/payment/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
